### ISSUE TITLE
Album art returns null

### ISSUE THREAD

**Issue by FullMoonFever** [JohnnyCrazy/SpotifyAPI-NET#158] opened 2017-06-22 14:18 UTC
I made an application to set the album art as the desktop background and everything worked properly. Today I wanted to improve some things, but the album art returns null. Normally I combine the album art and an other image, so the background isn't just black around the album art. But when I only use the album art and set it as the backgound by using the url of the image, it returns an empty string. I also checked if I have the latest version of the api installed.
![albumartissue_3](https://user-images.githubusercontent.com/20972334/27438378-5748b000-5765-11e7-81fc-af91a3381f01.PNG)
_Translation: "The value can not be null."_

![albumartissue_2](https://user-images.githubusercontent.com/20972334/27438292-0a8dbbac-5765-11e7-87d9-29feaa914064.PNG)
_Translation: "Invalid URI: The URI is empty. "_

**Comment by JohnnyCrazy** [comment] 2017-06-22 16:34
Duplicate of #155 , please use the search next time.

**Closed by JohnnyCrazy** 2017-06-22 16:34 UTC
