### ISSUE TITLE
Album art missing

### ISSUE THREAD

**Issue by nicoskia** [JohnnyCrazy/SpotifyAPI-NET#155] opened 2017-06-20 16:34 UTC
As of the latest Spotify update, the album art is no longer loading properly.

**Comment by aleab** [comment] 2017-06-20 16:52
Same issue. I've been working on a fix for the past hour.
The problem is that GetAlbumArtUrl always returns an empty string because the response from Spotify does not contain the expected meta tag, the one with "property=\"og:image\"".

![1](https://user-images.githubusercontent.com/11708634/27345089-bf77f43e-55e8-11e7-8e90-a5b7d1ec94d4.png)

Even if I add a User-Agent to the header of the request, the response still does not contain the meta tag, but the album art url is both in the head and in the body of the page.

![2](https://user-images.githubusercontent.com/11708634/27345149-ef1a8d78-55e8-11e7-8f2d-72d5ab9f6700.png)

**Comment by JohnnyCrazy** [comment] 2017-06-20 19:32
Fixed by #156 , gonna be released tomorrow afternoon

**Comment by JohnnyCrazy** [comment] 2017-06-22 16:44
[2.14.2](https://www.nuget.org/packages/SpotifyAPI-NET/2.14.2) is released. Although nuget needs some time to index it I guess..

**Closed by JohnnyCrazy** 2017-06-22 16:44 UTC
