### ISSUE TITLE
APIException on Search endpoint

### ISSUE THREAD

**Issue by Xythium** [JohnnyCrazy/SpotifyAPI-NET#731] opened 2022-02-04 14:45 UTC
Recently I started getting `APIException`s whenever I use `SpotifyClient.Search`. There doesn't seem to be any description in the exception

```
Unhandled exception. SpotifyAPI.Web.APIException: Exception of type 'SpotifyAPI.Web.APIException' was thrown.
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
```

**Comment by JohnnyCrazy** [comment] 2022-02-04 14:53
The exception has a `Response` field. Either have a look at that or the message field.

**Comment by Xythium** [comment] 2022-02-04 15:35
![image](https://user-images.githubusercontent.com/12112079/152556909-13f949af-acb2-4326-b175-b324f20f3ba7.png)

**Comment by Xythium** [comment] 2022-02-04 17:42
perhaps this isnt the right place to ask about this (maybe you know where that would be) but its literally just not returning anything and i dont really see any reason why that would happen

![image](https://user-images.githubusercontent.com/12112079/152576899-1bfe9221-52d9-4229-9dae-286e48700c8f.png)

**Comment by JohnnyCrazy** [comment] 2022-02-04 17:50
This looks like a legit request, very weird...

Did you catch this request with a proxy using this library or did you manually send it?

**Comment by Xythium** [comment] 2022-02-04 17:54
I used Fiddler to get that screenshot but it does the same thing without. I'm just using the library normally with `ClientCredentialsAuthenticator` & `SimpleRetryHandler`. The call for that request is 

```
var response = spotifyClient.Search.Item(new SearchRequest(SearchRequest.Types.Album, $"upc:{release.Barcode}"))
                .GetAwaiter()
                .GetResult();
```

but it seems to do it for every (occassionally it seems to go through without any issues) `SearchRequest`

**Comment by JohnnyCrazy** [comment] 2022-05-19 04:00
Due to the 404, I suspect that the issue is actually on spotify's side. It's especially confusing since the fiddler request looks valid. I will close this for now, if you have any more infos, feel free to share them and I will reopen! :)

**Closed by JohnnyCrazy** 2022-05-19 04:00 UTC
