### ISSUE TITLE
VideoAd crash

### ISSUE THREAD

**Issue by iUltimateLP** [JohnnyCrazy/SpotifyAPI-NET#41] opened 2015-10-02 08:56 UTC
Okey, ad update is fine thanks. Spotify implements in his newest version those video ads, which are popping up and are louder than normal :/
This leads the API to crash too. I debugged it to take a look what the TrackType is when the VideoAd plays, and its just empty then. Maybe you add a String.IsNullOrEmpty(TrackType) somewhere, to make this work..

**Comment by JohnnyCrazy** [comment] 2015-10-02 17:44
Video Ads? Wow. Can you give me full description on how the Track-Object looks like when this ad is played? I sadly can't reproduce since I never got any video ads on my free account (I was listening for about 2 hours :confused:)

**Comment by JimmyAppelt** [comment] 2015-10-02 18:43
Track-Object when video is playing

AlbumResource = null
ArtistResource = null
Length = 0
TrackResource = null
TrackType = null

:wink:

**Comment by iUltimateLP** [comment] 2015-10-03 15:55
Thanks @JimmyAppelt :+1:

**Comment by JimmyAppelt** [comment] 2015-10-05 09:57
Np @iUltimateLP  :facepunch: 

Btw: To invoke ads i close spotify and restart it, when playing the current song and forward it ... an ad will be played afterwards (95% of the time)

**Comment by JohnnyCrazy** [comment] 2015-10-09 18:26
Fixed in #42

**Closed by JohnnyCrazy** 2015-10-09 18:26 UTC
Labels: bug
