### ISSUE TITLE
Can´t connect to Spotify

### ISSUE THREAD

**Issue by ItsCoding** [JohnnyCrazy/SpotifyAPI-NET#258] opened 2018-07-26 17:31 UTC
Hey , i just tried to use your api but every time i want to connect threr comes no Information from Spotify. Even if i wanna try to controll spotify it doesn´t work :(

Tried on Windows 10 64bit and Windows Server 2016 64bit (different machines no VM)

**Comment by jscholes** [comment] 2018-07-26 18:16
Duplicate of #254.

**Closed** 2018-07-26 19:30 UTC
