### ISSUE TITLE
ResumePlayback & PausePlayback have JSON parse errors

### ISSUE THREAD

**Issue by gkapellmann** [JohnnyCrazy/SpotifyAPI-NET#1000] opened 2024-10-10 00:53 UTC
When calling these functions, there is a JSON error. The documentation seems to show that they return a Task<bool>, but the Spotify endpoint says there is no such response.

When running for example:
`public async Task Pause() {
    if (IsAvailable()) {
        try {
            await spotify.Player.PausePlayback();
        } catch (Exception ex) {
            Log.Exception(ex);
        }
    }
}`

There is an exception, notice that I removed the bool return, and yet still it throws an exception:

Unexpected character encountered while parsing value: h. Path '', line 0, position 0.
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: h. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonTextReader.Read()
         at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at SpotifyAPI.Web.Http.NewtonsoftJSONSerializer.DeserializeResponse[T](IResponse response)
         at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request, CancellationToken cancel)
         at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers, CancellationToken cancel)
         at SpotifyAPI.Web.Http.APIConnector.Put(Uri uri, IDictionary`2 parameters, Object body, CancellationToken cancel)
         at SpotifyAPI.Web.PlayerClient.PausePlayback(CancellationToken cancel)
         at VeronicaGen.Services.Audio.Spotify.SpotifyService.Pause() in C:\Users\gkapellmann\Documents\C#\Project_Veronica\Veronica_Support\Veronica_HostsGenerals\Veronica_Generals\VeronicaGen.Services\Audio\Spotify\SpotifyService.cs:line 234
         

The pause event still happens, so, somehow it is working. But still throuws this...

I am not sure if other Player functions are having the same problem besides resume and pause.

**Comment by JohnnyCrazy** [comment] 2024-10-12 22:18
Duplicate of #980

**Closed by JohnnyCrazy** 2024-10-12 22:18 UTC
