### ISSUE TITLE
API blocking UI thread

### ISSUE THREAD

**Issue by JimmyAppelt** [JohnnyCrazy/SpotifyAPI-NET#46] opened 2015-10-06 15:28 UTC
After a connection, when moving the main window, it seems that the API is blocking the UI thread on and off continuously.

**Comment by JohnnyCrazy** [comment] 2015-10-15 12:06
I'm just trying to reproduce this, but sadly I can't.
The window is moving fine while music is playing, no stuttering at all @JimmyAppelt

**Comment by JimmyAppelt** [comment] 2015-10-15 12:39
My god @JohnnyCrazy  ... i just tested all apps en they are indeed running fine. I'm a lazy computer restarter (might had something to do with that :-1: )

My apologies for bringing this issue up.

If in any case i see any kind of behavior back ... i'l triple check !

**Comment by JohnnyCrazy** [comment] 2015-10-15 12:47
No Problem!

Although you are correct, with `SynchronizingObject` set to the form, it will run in the UI-Thread. But since only one small request is made to localhost, it should be running in about 1-10ms which is no problem for the UI. Maybe I will change this someday. Closing #45 then :)

**Comment by JimmyAppelt** [comment] 2015-10-16 01:33
After all i wasn't drunk :smile: 

It appears on my machine if i'm running the example app or my own app for a longer period of time. 

The thing is that it interferes with other features in my own app, that will have a small time out before these update and the UI will not go smoothly ether.

As for the time being i compiled the a .dll with async and await for my app use as current solution.

Could you tell why you designed the project with everything as event updates ?

**Comment by JohnnyCrazy** [comment] 2016-07-06 08:16
I ran the example for about 30 minutes but sadly couldn't reproduce window lags or similar. Which system are you running it on?

I maybe have one idea, will push it to another branch and maybe you could test it out

@JimmyAppelt

**Comment by stuntguy3000** [comment] 2016-07-07 06:49
This is about a year old, I suspect its no longer an issue now. /tsk

**Comment by JohnnyCrazy** [comment] 2016-07-07 07:28
Generally, if SynchronizingObject is set, the tick event will be run on that UI Thread. If you don't want this, you can remove it and invoke on the ui thread in every event. This will execute the http request in a separate thread.

Reopen if you still have issues and

**Closed by JohnnyCrazy** 2016-07-07 07:28 UTC
Labels: bug, pending

**Comment by JimmyAppelt** [comment] 2016-07-07 22:38
Windows 10 64-bit

I needed to create another way to capture information from the local player itself.

Because of this issue and issue #51 :)

@stuntguy3000 such issue's don't magically disappear ;)

@JohnnyCrazy i would be happy to test it out, the only problem i have is issue #51 still
