### ISSUE TITLE
PaginateAll fails, some playlists return as null

### ISSUE THREAD

**Issue by FrankBJensen** [JohnnyCrazy/SpotifyAPI-NET#1013] opened 2024-12-01 12:08 UTC
Hi there.

An issue have turned up. That is, it has been working, now its not.

```
var allPages = await spotify.PaginateAll(page);
foreach (var pl in allPages)
{
    if (pl != null) // In case its null - eg Today's playlist didnt load
    {
        UserList upl = new UserList();
        upl.id = pl.Id;
        upl.uri = pl.Uri;
        upl.name = pl.Name;
        p.pList.Add(upl);
    }
}
```

allPages can return a number of playlists, eg. 8 pcs. The if (pl != null) I have just added, cause the new thing is, that the playlist can be null. Thus its not being loaded. This error turned up at all machines running my software, so something has changed. At first I thought, that it was due to special characters in the playlist name, cause I deleted today's playlist, and this machine worked again. But this must have been a lucky guess, cause I have another machine, where only 4 of 8 playlists are not null. And they contain no special characters.

Anyone knows, what is going on here?

**Comment by jenka1980** [comment] 2024-12-01 14:58
Hove same problem. I'm trying to get playlist by "spotify" user and response I get a 1015 null playlists.
Before 29/11/2024 everything worked perfectly.

**Comment by JohnnyCrazy** [comment] 2024-12-01 15:23
Duplicate of #1012

**Closed by JohnnyCrazy** 2024-12-01 15:23 UTC
