### ISSUE TITLE
Something wrong with version 1.0.74.380

### ISSUE THREAD

**Issue by ghost** [JohnnyCrazy/SpotifyAPI-NET#218] opened 2018-02-15 14:44 UTC
With this version problems started.

**Comment by Gruhlum** [comment] 2018-02-16 14:37
You have to be more specific.
An error that occures for me is that sometimes when the track changes OnTrackChange returns a new song that is not null, but the values are.

**Comment by aleab** [comment] 2018-02-16 14:48
@SomeOneMore what kind of problems? Can they be replicated in the example application in this repo?

@Gruhlum does that happen with podcasts or with normal songs? If it's podcasts, then it's expected behaviour.

**Comment by Gruhlum** [comment] 2018-02-16 15:32
@aleab normal songs. And no specific ones, the same song can work one time and the next it's broken again.

**Comment by aleab** [comment] 2018-02-19 13:09
@Gruhlum I think it's better if you create another issue until @SomeOneMore gives more info on theirs.

**Comment by JohnnyCrazy** [comment] 2018-02-20 19:31
Example app still works for me, and I don't understand the issue at all...

**Comment by Gruhlum** [comment] 2018-02-23 12:32
Yes the problem seems to be fixed now.

**Closed** 2018-03-11 23:15 UTC
