### ISSUE TITLE
RequestToken is not working after publishing to appstore

### ISSUE THREAD

**Issue by nightBaker** [JohnnyCrazy/SpotifyAPI-NET#841] opened 2022-12-11 18:25 UTC
It is how client is initialized
```
var config = SpotifyClientConfig.CreateDefault();

var request =
    new ClientCredentialsRequest("myclientId", "mySecret");
var response = await new OAuthClient(config).RequestToken(request);

_spotify = new SpotifyClient(config.WithToken(response.AccessToken));
```
and it works while debugging on emulator or device

However after I published it to TestFlight (AppStore), I get the error :
```
Error setting value to 'AccessToken' on 'SpotifyAPI.Web.ClientCredentialsTokenResponse'. at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[ClientCredentialsTokenResponse](String value, JsonSerializerSettings settings) at SpotifyAPI.Web.Http.NewtonsoftJSONSerializer.DeserializeResponse[ClientCredentialsTokenResponse](IResponse response) at SpotifyAPI.Web.Http.APIConnector.<DoSerializedRequest>d__30`1[[SpotifyAPI.Web.ClientCredentialsTokenResponse, SpotifyAPI.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() at SpotifyAPI.Web.Http.APIConnector.<SendAPIRequest>d__34`1[[SpotifyAPI.Web.ClientCredentialsTokenResponse, SpotifyAPI.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() at MyApp.Spotify.SpotifyService.RefreshClient() at MyApp.Spotify.SpotifyService.InitProvider() at MyApp.Pages.Market.OnInitializedAsync()
```

**Comment by iamcymentho** [comment] 2023-10-30 08:25
Hello @nightBaker 

How are you doing? I recently encountered issue #841 with the Spotify API client library and noticed that it has not been resolved. I am interested in contributing to the resolution of this issue, and I wanted to inquire about its current status.

The issue description mentions **[RequestToken is not working after publishing to appstore]**(https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/841#top). I believe I can provide some assistance in resolving it.

If there have been any updates or progress on this issue, please let me know. I would appreciate any guidance or information you can provide.

If the issue is still open and you would like assistance in addressing it, I am willing to contribute to the development effort. Please let me know how I can get involved, whether it's by providing code, testing, or assisting in any other way.

Thank you for your time and consideration. I look forward to your response.

Best regards,

**Comment by JohnnyCrazy** [comment] 2024-02-10 11:44
Hi,

Sorry for not having responded here, if it's still an issue, feel free to re-open or open another issue!

**Closed by JohnnyCrazy** 2024-02-10 11:44 UTC
