### ISSUE TITLE
SpotifyAPI.Web.APIException: Server error when calling Tracks.Get()

### ISSUE THREAD

**Issue by rhiskey** [JohnnyCrazy/SpotifyAPI-NET#756] opened 2022-04-13 12:24 UTC
Steps to reproduce:

```csharp
 var config = SpotifyClientConfig
              .CreateDefault()
              .WithAuthenticator(new ClientCredentialsAuthenticator(SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET));
 var api = new SpotifyClient(config);

// Try to get IPlayableItem
 track = await api.Tracks.Get("7CsdHQZlVcksVMwGlvulD0"); // here throws exception
```

```csharp
SpotifyAPI.Web.APIException: Server error.
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at spotytovkshare_backend.Controllers.Spotify2Controller.GetSearchName(String uri) in M:\GitHub\spotytovkshare_backend\Controllers\SpotifyController.cs:line 175
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
Implelentation:
https://github.com/rhiskey/spotytovkshare_backend/blob/a0a1d07e88adbea4a2fd3b9abedba6c5e4682104/Controllers/SpotifyController.cs#L172

**Comment by JohnnyCrazy** [comment] 2022-04-13 12:41
Hi,

Is the paramter really a spotify `id` or an `uri`? `uri` contains `spotify:...` etc. and can not be used with `Tracks.Get`.

**Comment by rhiskey** [comment] 2022-04-13 12:49
> Hi,
> 
> Is the paramter really a spotify `id` or an `uri`? `uri` contains `spotify:...` etc. and can not be used with `Tracks.Get`.

Hi!
This parameter is an existing spotify ID, which was extracted from URI https://open.spotify.com/track/7CsdHQZlVcksVMwGlvulD0

In any case, this error does not always occur. I believe this is due to spotify blocking in some regions, but I'm not sure.

**Comment by JohnnyCrazy** [comment] 2022-05-19 04:04
I will recheck within next week if it's maybe related to the `ClientCredentialsAuthenticator`, although I doubt it

**Comment by JohnnyCrazy** [comment] 2022-06-06 12:22
So I tried to reproduce it with `ClientCredentialsAuthenticator`, but was unable to.

```c#
      SpotifyClientConfig config = SpotifyClientConfig.CreateDefault().WithAuthenticator(new ClientCredentialsAuthenticator(
        "ClientId", "ClientSecret"
      ));

      SpotifyClient spotify = new(config);
      FullTrack track = await spotify.Tracks.Get("2KqwH2jVrO4rjYJ6O6XTLO");

      Console.WriteLine(track.Name);
```

Due to the fact that the error just says `Server Error`. I would also assume something is wrong on Spotify's end. If there would be sth wrong with the token, which we can fix, it would be some kind of `invalid_access_token` error.

I'm closing it for now, but feel free to contact spotify in the forums and update us here!

**Closed by JohnnyCrazy** 2022-06-06 12:22 UTC
Labels: pending

**Comment by rhiskey** [comment] 2022-06-06 13:34
> So I tried to reproduce it with `ClientCredentialsAuthenticator`, but was unable to.
> 
> ```cs
> SpotifyClientConfig config = SpotifyClientConfig.CreateDefault().WithAuthenticator(new ClientCredentialsAuthenticator(
>   "ClientId", "ClientSecret"
> ));
> 
> SpotifyClient spotify = new(config);
> FullTrack track = await spotify.Tracks.Get("2KqwH2jVrO4rjYJ6O6XTLO");
> 
> Console.WriteLine(track.Name);
> ```
> 
> Due to the fact that the error just says `Server Error`. I would also assume something is wrong on Spotify's end. If there would be sth wrong with the token, which we can fix, it would be some kind of `invalid_access_token` error.
> 
> I'm closing it for now, but feel free to contact spotify in the forums and update us here!

 Ok, good to hear that is not your's client problem
