### ISSUE TITLE
Compatibility with UWP

### ISSUE THREAD

**Issue by pablojim99** [JohnnyCrazy/SpotifyAPI-NET#189] opened 2017-10-24 14:10 UTC
I don't know if anyone was able to use SpotifyAPI-NET with an Universal Windows Platform (UWP) app but every time I try to install nuget packages in my UWP Project I get an error. Is it possible right now? If not, any chances of seeing it in the future?
Thanks!

**Comment by JohnnyCrazy** [comment] 2017-10-24 14:42
Duplicate of #169

**Closed by JohnnyCrazy** 2017-10-24 14:42 UTC

**Comment by pablojim99** [comment] 2017-10-24 19:36
So what i'm supposed to do? How do I use the "core-3" branch using NuGet packages?

**Comment by JohnnyCrazy** [comment] 2017-10-24 19:57
There is no nuget package because it's still WIP and probably outdated. Clone it and try to build it.

And if it doesn't work, this library may not be for your usecase

**Comment by pablojim99** [comment] 2017-10-24 20:53
Okey thanks, I'll try and tell you if it works. Did you know any API for Spotify that works with UWP?
