### ISSUE TITLE
Null follower total on /v1/me/top/artists

### ISSUE THREAD

**Issue by CVertex** [JohnnyCrazy/SpotifyAPI-NET#89] opened 2016-07-05 07:25 UTC
Howdy,

I've noticed that called /me/top/artists using this lib causes a deserialization exception on the Followers object. 
If you look at the json of the error, it appears many (if not all) artists don't come back with follower counts. Does everyone else see the same thing?

Here's an example artist from my top artist list
http://www.jsoneditoronline.org/?id=145f4fa2c2c61727d29794e3fa5e8b08
Notice the null follower.total.
If I get the artist info from the artist lookup endpoint, i see the follower count.

![image](https://cloud.githubusercontent.com/assets/120773/16576888/57f410a8-42d5-11e6-8f36-1e5d5f188a4f.png)

Should I report this to Spotify, or should we make follower total nullable?

Thanks

**Comment by JohnnyCrazy** [comment] 2016-07-05 09:11
Hi,

Since its not documented that the follower can be null, I would report it at their wep-api repo. If it's expected, we should change it, however I think it's a bug on spotifys side

**Comment by JimmyAppelt** [comment] 2016-07-05 09:43
Yes it should be reported, i assume this is unexpected behavior. Like Johnny says (it's not documented). The artist in particular has at the time of writing 16802 followers.

**Comment by CVertex** [comment] 2016-07-05 09:58
Makes sense. 
I've reported it to their twitter account, https://twitter.com/CVertex/status/750266863376998400

I've had this reporting approach work in the past. Do you see the same thing?

Thanks

**Comment by JimmyAppelt** [comment] 2016-07-05 10:01
@CVertex the correct page to document a possible bug will be [https://github.com/spotify/web-api](https://github.com/spotify/web-api)

**Comment by thelinmichael** [comment] 2016-07-05 11:09
Thanks for reporting this @CVertex, and for following up on Twitter @JohnnyCrazy. We'll take a look at it! I've created a new [issue in the /spotify/web-api repository](https://github.com/spotify/web-api/issues/261) to track it.

**Comment by JohnnyCrazy** [comment] 2016-07-05 11:25
Thanks @thelinmichael ,closing this in favor of `spotify/web-api#261`

**Closed by JohnnyCrazy** 2016-07-05 11:25 UTC
