### ISSUE TITLE
"Retry-After" header not present in response with error code 429.

### ISSUE THREAD

**Issue by svenrog** [JohnnyCrazy/SpotifyAPI-NET#124] opened 2016-12-05 09:28 UTC
When the API becomes rate limited, spotify returns a header with the wait time as described here.

https://developer.spotify.com/web-api/user-guide/#rate-limiting

This value is not present in the response returned when querying.

**Comment by JackRyder** [comment] 2016-12-05 12:04
This has already been raised, see here: [https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/113](url)

**Comment by svenrog** [comment] 2016-12-05 12:19
Thanks for the info, but afaik you can retrieve a response from the WebException, since it contains a response.
https://msdn.microsoft.com/en-us/library/b2zywh13(v=vs.110).aspx

I'll look into this for you.

**Comment by JohnnyCrazy** [comment] 2016-12-06 17:50
Closing as duplicate of #113

**Closed by JohnnyCrazy** 2016-12-06 17:50 UTC
