### ISSUE TITLE
Search for '#' produces error

### ISSUE THREAD

**Issue by Joniator** [JohnnyCrazy/SpotifyAPI-NET#143] opened 2017-04-14 21:26 UTC
WebApi.SearchItems creates {SpotifyAPI.Web.Models.Error}, Status 400, Message "Missing parameter type" if the parameter contains '#' at any position.

**Comment by JohnnyCrazy** [comment] 2017-04-14 22:33
Duplicate of #131 

For the time, `URLEncode` the query parameter before you pass it to the method

**Closed by JohnnyCrazy** 2017-04-14 22:33 UTC
